name: CD

on:
  workflow_run: 
    workflow: [CI]
    types:
      - completed

jobs:
  CD:
    name: Continuos Delivery
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    setps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: